# Generated by Django 3.1.1 on 2020-09-26 06:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20200530_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='display_factor',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10),
        ),
    ]
