# Generated by Django 3.1.1 on 2020-11-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20201108_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('order_no',)},
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='order_no',
            field=models.FloatField(default=1),
        ),
    ]
