# Generated by Django 3.1.1 on 2020-11-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20201114_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-view_count',)},
        ),
        migrations.AddField(
            model_name='recipe',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
