# Generated by Django 3.1.1 on 2021-02-06 11:55

from django.db import migrations, models
import django.db.models.deletion
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_recipe_last_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeInstanceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=recipe.models.RecipeInstanceImage.image_path)),
                ('recipe_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipe.recipeinstance')),
            ],
        ),
    ]
